name: Build and Push Docker Image

on:
  push:
    branches:
      - release  # Solo se ejecuta cuando hay un push a release
    tags:
      - "v*"  # También se ejecuta cuando se crea un tag con el formato "vX.Y.Z"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Loguearse en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Obtener versión del tag o commit
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(date +'%Y%m%d')-$(git rev-parse --short HEAD)
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Construir y subir la imagen Docker con etiquetas
        run: |
          docker build --platform linux/amd64 -t tmrafa/cactushr_bot:latest -t tmrafa/cactushr_bot:$VERSION .
          docker push tmrafa/cactushr_bot:latest
          docker push tmrafa/cactushr_bot:$VERSION