name: Create Release

# Allow the workflow to be triggered manually
on:
  workflow_dispatch:

jobs:
  merge-main-into-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Ensure release branch exists
        run: |
          if ! git show-ref --verify --quiet refs/heads/release; then
            git checkout -b release
            git push origin release
          else
            git checkout release
          fi

      - name: Merge main into release
        run: |
          git checkout release
          git merge main
          git push origin release